services:
  postgres:
    image: postgres:16
    container_name: vm_orchestrator_poc_db
    environment:
      POSTGRES_DB: vm_orchestrator_poc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 